scalar UUID
scalar JSON
scalar Date
scalar Void

type Mutation {
  createStock(symbol: String!): Stock
  deleteStock(id: UUID!): UUID
}

type Query {
  stocks: [Stock]
}

type Subscription {
  stockAdded: Stock
  stockDeleted: UUID
}

type Stock {
  id: UUID!
  symbol: String!
  price: Float!,
  company: String!,
  chart: [ChartValue],
}

type ChartValue {
  x: Date
  y: Float
}