scalar UUID
scalar JSON
scalar Date
scalar Void

type Mutation {
  createStock(id: String!): Stock
  deleteStock(id: String!): UUID
}

type Query {
  stocks: [Stock]
}

type Stock {
  id: String!
  price: Float!,
  company: String!,
  chart: [ChartValue],
}

type ChartValue {
  x: Date
  y: Float
}
